defaults: &defaults
  docker:
    - image: klembara/swift4:0.0.1


version: 2.0
jobs: 
  resolve:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: swift package resolve

  build_debug:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: swift build

  build_release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: swift build -c release

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .build
      - run:
          name: Run unit tests
          command: swift test --parallel
workflows:
  version: 2
  resolve_build_and_test:
    jobs:
      - resolve
      - build_debug:
          requires:
            - resolve
      - build_release:
          requires:
            - resolve
      - test:
          requires:
            - build_release
            - build_debug
