version: 2.0
jobs: 
  resolve:
    docker:
      - image: klembara/swift4:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Build
          command: |
           swift package resolve
           swift package update
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
          paths:
            - .build/

  build_debug:
    docker:
      - image: klembara/swift4:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Build
          command: |
           swift build
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
          paths:
            - .build/
  build_release:
    docker:
      - image: klembara/swift4:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Build
          command: |
           swift build -c release
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
          paths:
            - .build/

  test:
    docker:
      - image: klembara/swift4:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Run unit tests
          command: |
            swift test --parallel
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
          paths:
            - .build/

workflows:
  version: 2
  resolve_build_and_test:
    jobs:
      - resolve
      - build_debug:
          requires:
            - resolve
      - build_release:
          requires:
            - resolve
      - test:
          requires:
            - build_debug
            - build_release

