defaults: &defaults
  docker:
    - image: klembara/swift4:0.0.1


version: 2.0
jobs: 
  resolve:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Build
          command: |
           swift package resolve
           swift package update
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
          paths:
            - .build/
            - Package.resolved
      - persist_to_workspace:
          root: .build
          paths:
            - checkouts
            - repositories

  build_debug:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .build
      - run:
          name: Build
          command: |
           swift build
      - persist_to_workspace:
          root: .build
          paths:
            - checkouts
            - repositories
            - x86_64-unknown-linux/debug

  build_release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .build
      - run:
          name: Build
          command: |
            swift build -c release

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .build
      - run:
          name: Run unit tests
          command: |
            swift test --parallel

workflows:
  version: 2
  resolve_build_and_test:
    jobs:
      - resolve
      - run:
        - name: Find
        - command: |
          find .build -type d

      - build_debug:
          requires:
            - resolve
      - build_release:
          requires:
            - resolve
      - test:
          requires:
            - build_debug
            - build_release

